var _fxcmd=_fxcmd||[];
(function(){function q(){var a="";try{a=window.top.document}catch(b){if(window.parent)try{a=window.parent.document}catch(c){a=""}}""===a&&(a=document);return a}function r(){if(!k.isCache()&&(!0===_fxcmd.trackAll||""!=this.params.fxfc)){var a=[];this.spliceParams(this.params,a);0<this.vars.length&&this.spliceParams({fxcup:"[["+this.vars.join("],[")+"]]"},a);this.goods&&(this.spliceParams(this.goods,a),delete this.goods);this.odrs&&(this.spliceParams(this.odrs,a),delete this.odrs);this.evts&&(this.spliceParams({fxcep:'["'+
this.evts.join('","')+'"]'},a),delete this.evts);this.wc&&(this.spliceParams(this.wc,a),delete this.evts);this.llnk&&(this.spliceParams({fxlink:this.llnk},a),delete this.llnk);var b=new Image(0,0);b.onload=function(){};b.onerror=function(){};var c=e._reqUrl.indexOf("?");b.src=e._reqUrl+(-1<c?c===e._reqUrl.length-1?"":"&":"?")+a.join("&")+("&_ts="+(new Date-1));this.sended=!0}}function u(){this.params={};this.vars=[]}if("function"!==typeof _fxcmd._getFx||!_fxcmd._getFx()){_fxcmd.getVersion=function(){return"20140418"};
var e={_ts:+new Date,_cookiePrefix:"_pzfx",_cookieDeli:"|",_cookieTimeout:_fxcmd.ct||10512E3,_sessionTimeout:_fxcmd.st||20,_fcTimeout:_fxcmd.fct||2880,_cookieKey:{uv:"uvpc",sv:"svpc",oi:"oinf",fc:"sfc",domain:"dm"},_reqUrl:_fxcmd.requestUrl||"//fx.w3t.cn/fx/jsServlet3",_reqWcSrc:_fxcmd.webCallSrc||"//static.w3t.cn/fx/1/1/fxwc.js"},z=encodeURIComponent,A=decodeURIComponent,k={isDefine:function(a){return"undefined"!==typeof a},isFunction:function(a){return"function"!==typeof a},isCache:function(){var a=
q().location.href,b=!1;-1<a.indexOf("cache.baiducontent.com")?b=!0:-1<a.indexOf("webcache.googleusercontent.com")?b=!0:-1<a.indexOf("www.sososnap.com")?b=!0:-1<a.indexOf("c.360webcache.com")?b=!0:-1<a.indexOf("www.youdao.com/cache")&&(b=!0);return b},isSiteLink:function(a){if(!a)return!1;if(0!==a.indexOf("http"))return!0;var b=location.port;return(new RegExp("^http(s)?\\:\\/\\/(.+\\.)*"+document.domain+(b?"\\:"+b:"")+"(\\/|$)")).test(a.split("?")[0])},checkDomain:function(a){var b=/^http(?:s)?\:\/\/((?:[\w\d]+(?:-+[\w\d]+)*\.)+([\w\d]+(-+[\w\d]+)*\.)?(test|com|net|org|hk|cn|com\.cn|net\.cn|org\.cn|gov\.cn|biz|info|cc|tv|mobi|name|asia|tw|sh|ac|io|tm|travel|ws|us|sc|mn|ag|vc|la|bz|in|cm|co|tel|me|pro|com\.hk|com\.tw|pw)|(((\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.){3}(\d{1,3}|1\d\d|2[0-4]\d|25[0-5])))(\:\d+)?/;
a=/([^\.]+\.(test|com|net|org|hk|cn|com\.cn|net\.cn|org\.cn|gov\.cn|biz|info|cc|tv|mobi|name|asia|tw|sh|ac|io|tm|travel|ws|us|sc|mn|ag|vc|la|bz|in|cm|co|tel|me|pro|com\.hk|com\.tw|pw)(\:\d+)?$)|(((\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.){3}(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])(\:\d+)?$)/;return b.exec(location.href)?(b=b.exec(location.href)[1],(b=a.exec(b)[1]||a.exec(b)[0])||""):""}},l={set:function(a,b,c){var d,v=f.domain,v=k.checkDomain(v);c&&(d=new Date,d.setTime(d.getTime()+6E4*c));a=a||"";a=0===a.indexOf(e._cookiePrefix)?
a:e._cookiePrefix+a;document.cookie=a+"="+z(b)+(c?";expires="+d.toUTCString():"")+";path=/;domain="+v},get:function(a){var b="";return a?(a=0===a.indexOf(e._cookiePrefix)?a:e._cookiePrefix+a,a=new RegExp("(?:^|;) *"+a+"=([^;]*?)(?:$|;)"),(a=a.exec(document.cookie))&&(b=A(a[1])),b):document.cookie},check:function(a){return a?RegExp("(^|;) *"+e._cookiePrefix+a+"=").test(document.cookie):!1}},f={removeHash:function(a){var b=a.indexOf("#");-1<b&&(a=a.slice(0,b));return a},splitUrl:function(a){var b=a=
f.removeHash(a),c=/.*?:\/\/(.*?)\/.*/.exec(a);a=a.split("?")[1];c=c?c[1]:"";return{url:b,host:c,search:a||""}},getMate:function(a){a=f.removeHash(a);var b=f.splitUrl(a);a=b.url;var c=b.host,b=b.search||"",d="",e="",d="",w;-1<c.indexOf(".baidu.com")?(d=-1<b.indexOf("word=")?"word=":"wd=",e="baidu"):-1<c.indexOf("www.google.")?(d="q=",e="google"):-1<c.indexOf(".soso.com")?(d=-1<b.indexOf("syn=")?"syn=":-1<b.indexOf("query=")?"query=":-1<b.indexOf("sp=S")?"sp=S":"w=",e="soso"):-1<c.indexOf(".haosou.com")?
(d=-1<b.indexOf("kw=")?"kw=":-1<b.indexOf("k=")?"k=":"q=",e="360"):-1<c.indexOf(".sogou.com")&&(-1<b.indexOf("query=")?d="query=":-1<b.indexOf("keyword=")?d="keyword=":-1<b.indexOf("w=")?d="w=":-1<b.indexOf("sp=S")&&(d="sp=S"),e="sogou");e&&d&&(w=(new RegExp("(?:^|&)"+d+"([^&]*)(?:&|$)")).exec(b));d=w?w[1]:"";return{url:a,host:c,search:b,kw:d,se:e}},trackHref:function(){if(!f._hrefSetting){var a=f.splitUrl(location.href);f._refSetting||f.trackReferrerInfo();f.domain=document.domain;f.host=a.host;
f._hrefSetting=!0}}},g={filterMimeTypes:function(){var a=navigator.mimeTypes,b=!1,c={java:{name:"Java",type:"application/x-java-vm"},swf:{name:"Flash",type:"application/x-shockwave-flash"},spl:{name:"Flash",type:"application/futuresplash"}},d,e,f;if(k.isDefine(a)&&0<a.length)if(e=a.length,b=!!a[a[0].type])for(d in c)b=c[d],g[b.name]&&"0"!==g[b.name]||(g[b.name]=a[b.type]?"1":"0");else for(d=0;d<e;d++)b=a[d],(f=c[b.suffixes])&&b.type===f.type&&!g[f.name]&&(g[f.name]="1")},hasCookie:function(){var a=
navigator.cookieEnabled?"1":"0";k.isDefine(navigator.cookieEnabled)||(l.set("TempCookie__","1"),a="1"===l.get("TempCookie__")?"1":"0");return a},hasJava:function(){if(k.isDefine(g.Java))return g.Java;var a="0";try{k.isFunction(navigator.javaEnabled)&&navigator.javaEnabled()&&(a="1")}catch(b){}return a},hasFlash:function(){var a="0",b,c;if(-1<navigator.userAgent.toUpperCase().indexOf("MSIE"))try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),b=c.GetVariable("$version").split(" ")[1].split(","),
a=b[0]+"."+b[1]+" r"+b[2]}catch(d){}else"1"===g.Flash&&k.isDefine(navigator.plugins)&&0<navigator.plugins.length&&(b=navigator.plugins["Shockwave Flash"])&&(a=b.description.split("Shockwave Flash ")[1]);return a}},n={getUniqueId:function(){return(e._ts*Math.random()).toString().slice(0,10)+(e._ts*Math.random()).toString().slice(0,9)},isNewSession:function(){return l.check(e._cookieKey.sv)?"0":"1"},getUserInfo:function(){var a=l.get(e._cookieKey.uv),b,c,d,f,g,k;a?(a=a.split(e._cookieDeli),b=a[0],c=
a[1],d=a[2],f=a[3],g=a[4],k=a[5],a=a[6]):(b=e._ts,c=n.getUniqueId(),d=0,f=e._ts,g=0,a=k="");return{fvTs:parseInt(b),uid:c,pvCount:parseInt(d),lastPvTs:parseInt(f),curPvTs:e._ts,sessionCount:parseInt(g),lastSessionId:k,sessionId:a}},getSessionInfo:function(){var a=l.get(e._cookieKey.sv),b,c,d;a?(a=a.split(e._cookieDeli),b=a[0],c=a[1],d=a[2],a=a[3]):(c=e._ts,b=n.getUniqueId(),d=0,a="undefined"!==typeof f.ref?f.ref:f.removeHash(document.referrer));return{sessionId:b,sessionTs:parseInt(c),sessionPvCount:parseInt(d),
sessionRef:a}},setUvCookie:function(a){l.set(e._cookieKey.uv,a.join(e._cookieDeli),e._cookieTimeout)},setSvCookie:function(a){l.set(e._cookieKey.sv,a.join(e._cookieDeli),e._sessionTimeout)}};u.prototype={constructor:u,init:function(){this.initParams()},getSI:function(){var a=this.params;a.fxac=_fxcmd.sid||"";a.fxmedium=_fxcmd.medium||"";a.fxclient=_fxcmd.client||"0";a.fxct=e._cookieTimeout;a.fxst=e._sessionTimeout},getTI:function(){f.trackHref();var a=this.params,b=n.getUserInfo(),c=n.getSessionInfo();
a.fxvid=b.uid;a.fxfvts=b.fvTs;a.fxts=b.curPvTs;a.fxlrts=b.lastPvTs;a.fxdsfs=Math.floor((b.curPvTs-a.fxfvts)/24/60/60/1E3);a.fxvpv=b.pvCount;a.fxdomain=q().location.host;a.fxhref=f.refHost&&f.refHost!==f.host?"1":"0";a.fxsid=c.sessionId;a.fxsts=c.sessionTs;a.fxspv=c.sessionPvCount;a.fxsref=c.sessionRef;a.fxsrefts=a.fxsref?"1":"0";a.fxisn=n.isNewSession();a.fxinv=a.fxspv===a.fxvpv?"1":"0";"1"===a.fxisn?(a.fxpsid=b.sessionId,a.fxv=b.sessionCount+1):(a.fxpsid=b.lastSessionId,a.fxv=b.sessionCount);var b=
/.*[&?]fc=([^&]+).*/.exec(q().location.href),d=/^http(?:s)?\:\/\/(?:(?:[\w\d]+(?:-+[\w\d]+)*\.)+([\w\d]+(-+[\w\d]+)*\.)(com|net|org|hk|cn|com.cn|net.cn|org.cn|gov.cn|biz|info|cc|tv|mobi|name|asia|tw|sh|ac|io|tm|travel|ws|us|sc|mn|ag|vc|la|bz|in|cm|co|tel|me|pro|com.hk|com.tw|pw)|(((\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.){3}(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])))(\:\d+)?/,b=b&&b[1],c=d.exec(location.href),d=d.exec(document.referrer);c&&d?(c.shift(),d.shift(),a.fxland=c.join("")===d.join("")?"0":1):a.fxland=
"1";b||(b=l.get(e._cookieKey.fc));a.fxfct=e._fcTimeout;a.fxfc=b?A(b):""},updateTInfo:function(){var a=this.params;e._ts=+new Date;a.fxvpv++;a.fxspv++;a.fxts=e._ts;n.setUvCookie([a.fxfvts,a.fxvid,a.fxvpv,a.fxts,a.fxv,a.fxpsid,a.fxsid]);n.setSvCookie([a.fxsid,a.fxsts,a.fxspv,a.fxsref]);/.*[&?]fc=([^&]+).*/.test(q().location.href)&&l.set(e._cookieKey.fc,a.fxfc,e._fcTimeout)},getPI:function(){var a=this.params;g.filterMimeTypes();a.fxck=g.hasCookie();a.fxje=g.hasJava();a.fxfl=g.hasFlash()},getUM:function(){if(!f._refSetting){var a=
this.params,b=f.getMate(q().referrer);f.refHost=b.host;f.ref=b.url;a.fxuref=b.url;a.fxterm=b.kw;a.fxsource=b.se;f._refSetting=!0}},getVI:function(){var a=this.params,b=document,c=b.body,d=b.documentElement,e=screen;a.fxcs=(b.charset||b.characterSet||"").toLowerCase();a.fxsc=parseInt(e.pixelDepth||e.colorDepth||"");a.fxdt=b.title;a.fxsr=e.width+"x"+e.height;a.fxvp=Math.min(c.clientWidth,d.clientWidth)+"x"+Math.min(c.clientHeight,d.clientHeight);a.fxpw=Math.max(c.scrollWidth,d.scrollWidth);a.fxph=Math.max(c.scrollHeight,
d.scrollHeight)},initParams:function(){this.getSI();this.getPI();this.getUM();this.getVI();this.getTI();this.updateTInfo()},customVar:function(a,b,c,d,e){"undefined"!==typeof a&&"undefined"!==typeof b&&this.vars.push('"'+[a,b,c,d,e].join('","')+'"')},trackOrder:function(a,b){if("object"===typeof a){var c="oid u_info u_type ofare otp otax oci ost oco odis opay odesc profit coupon".split(" "),d=c.length,f=[],g=[],k=[],h,m;for(m=0;m<d;m++)h=c[m],"undefined"!==typeof a[h]&&f.push(h+':"'+a[h]+'"');if(b)for(h in d=
b.length,b[0])if(b[0].hasOwnProperty(h))for(k.push('"'+h+'"'),m=0;m<d;m++)c=g[m]||[],c.push('"'+(b[m][h]||"")+'"'||""),g[m]=c;this.odrs={fxpp:"ec",fxorder:"{"+f.join(",")+"}",fxoitems:"[["+g.join("],[")+"]]",fxomap:"["+k.join()+"]",fxlpts:l.get(e._cookieKey.oi)};l.set(e._cookieKey.oi,+new Date,e._cookieTimeout);this.sended&&r.call(this)}},trackGoods:function(a,b,c){this.goods={fxpks:a,fxpkn:b,fxpkc:c};this.sended&&r.call(this)},trackEvent:function(a,b,c,d){"undefined"!==typeof a&&"undefined"!==typeof b&&
(this.evts=[a,b,c,d],this.sended&&r.call(this))},trackLink:function(a){k.isSiteLink(a)||(this.llnk=a,this.sended&&r.call(this))},trackPage:function(){r.call(this)},trackCall:function(a,b){if(a&&(this._wbType=a,this._wbChart="undefined"!==typeof b?b:!1,!this.wcLoaded)){var c=document.createElement("script");c.type="text/javascript";c.async=!0;c.src=e._reqWcSrc;var d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(c,d)}},spliceParams:function(a,b,c){var d,e;c="undefined"===typeof c?
!0:c;for(d in a)a.hasOwnProperty(d)&&"undefined"!==typeof a[d]&&null!==a[d]&&""!==a[d]&&(e=a[d],"undefined"===typeof e||null===e?e="":c&&(e=z(e)),b.push(d+"="+e))}};var x;x=document.addEventListener?function(a,b,c){"complete"===document.readyState&&a===window&&"load"===b?c():a.addEventListener(b,c,!1)}:function(a,b,c){"complete"===document.readyState&&a===window&&"load"===b?c():a.attachEvent("on"+b,c)};var p=new u,y=_fxcmd.length,t,h;_fxcmd.push=function(a){if(a){var b=a[0];b&&p[b]&&p[b].apply(p,
a.slice(1))}};p.init();for(h=0;h<y;h++)_fxcmd.push(_fxcmd[h]);p.trackPage();_fxcmd._getFx=function(){return p};x(window,"load",function(){var a=document.body.getElementsByTagName("a");y=a.length;for(h=0;h<y;h++)t=a[h],k.isSiteLink(t.href)||t.target&&"_blank"===t.target||x(t,"click",function(a){p.trackLink(a.srcElement?a.srcElement.href:this.href)})})}})();